spring.application.name=inkinject

# URL de conexión a la base de datos PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/inkinject}

# Nombre de usuario para la base de datos
spring.datasource.username=${DB_USERNAME:postgres}

# Contraseña para la base de datos
spring.datasource.password=${DB_PASSWORD:postgres}

# Controlador para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para actualizar automáticamente el esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL ejecutadas en consola
spring.jpa.show-sql=true

# Puerto del servidor
server.port=${SERVER_PORT:8080}

# Clave secreta para JWT
jwt.secret=${JWT_SECRET:InkInjectClaveSecreta123}

# Tiempo de expiración del token JWT en milisegundos (1 día)
jwt.expiration=${JWT_EXPIRATION:86400000}

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs